### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by edmorbius** [Encrypt-S/navpi#28]
Hi

I am sorry if this is covered elsewhere but I must have missed this.  Can NavPi be installed on a Pi 2?  The instructions cover Pi 3 but don't explicitly cover minimum requirements.  I am asking because I have several Pi 2s laying around.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-24T12:25:42+13:00","ped":"2018-01-25T05:34:17+13:00"})

**Comment by DenisSa** [comment]
Hello,

Navpi can not be installed on pi2 due to lack of RAM.

Here are my stats for rpi3, as you can see 1gb of RAM is barely enough as is.

```
             total       used       free     shared    buffers     cached
Mem:           923        881         42          1         15         57
-/+ buffers/cache:        808        115
Swap:           99         97          2

```

The daemon takes up the vast majority of that memory.


What you could try is creating a large swap file, however depending on sdcard or usb drive performance you may not be able to sync up. I haven't tried this method.

**Comment by matt-auckland** [comment]
I've ran the image on a pi2 for a quick test of something. It seemed to work alright, but this was without an internet connection, so I'm not sure how well it functions with one. I suspect that once it starts syncing and checking txs and blocks the ram needed rises.

I'm going to close this issue, as it seems to be 'solved'.
