### ISSUE TITLE
Visual unlocked for staking bug

### ISSUE THREAD

**Issue by colvano** [Encrypt-S/navpi#9]
After updating the NavPi it shows: "the wallet is unlocked for staking"

This is not the case, it is locked after update script. Unlocking the wallet for staking again will unlock it.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by proletesseract** [comment]
Same thing if you reboot the device. Not sure what to do here. I do want to resolve this though.

**Comment by Satoshinaire** [comment]
I haven't noticed this issue only on reboot, but I believe the problem is `NavCoinlockstate.php` has been checked into the main repo with `Unlocked For Staking` as the contents. So any update may overwrite the local change.

This file should really be removed from the repo, added a `.gitignore`, and appropriate checks done to set default state.

**Comment by proletesseract** [comment]
yes, we will remove it from the repo and add to git ignore. thanks!
